language: python

python:
  - "2.7"

before_install:
    - sudo apt-add-repository ppa:linuxjedi/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -y libattachsql1 libattachsql1-dev
    - mysql -uroot -e "create database test;"
    - mysql -uroot -e "grant all on *.* to 'test'@'localhost' identified by 'test';"

install:
  - "pip install -r requirements.txt"

script: tox
